# Generated by Django 3.1 on 2020-11-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200530_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Access',
        ),
    ]
